all: build

build:
	(cd nninterpolation && cargo build)
	(cd interactivedemo && cargo build)

update:
	(cd nninterpolation && cargo update)
	(cd interactivedemo && cargo update)

clean:
	(cd nninterpolation && cargo clean)
	(cd interactivedemo && cargo clean)
