all: build

build:
	(cd nninterpolation && cargo build)
	(cd rtreevis && cargo build)

update:
	(cd nninterpolation && cargo update)
	(cd rtreevis && cargo update)

clean:
	(cd nninterpolation && cargo clean)
	(cd rtreevis && cargo clean)
